x-project:
  name: ess-alpine

services:
  webapp:
    build:
      context: ./webapp
    restart: unless-stopped
    environment:
      DB_HOST: $EXTERNAL_DB_HOST
      DB_USER: $PSQL_USER
      DB_USER_PW: $PSQL_ROOT_PASSWORD
      DB_NAME: $PSQL_DATABASE
      DB_PORT: $EXTERNAL_DB_PORT
    networks:
      - backend

  nginx:
    image: nginx:latest
    depends_on:
      - webapp
    ports:
      - $LOCAL_PORT:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend

networks:
  backend:
